### ISSUE TITLE
Forcegraph and d3 in extra module and load via requrie

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#1]
Provide a second js file and load if it is required

**Comment by xf-** [comment]
I close this for now. d3 update includes modular structure of d3. Less modules are loaded. Also size already decreased a lot.

**Comment by genofire** [comment]
That is no reason, why you close this issue.
Is the reason that this change would be to much work and changes?

**Comment by genofire** [comment]
Ups verwechselt mit #4 - allright :+1:
