### ISSUE TITLE
Add localStorage in forcegraph again

### ISSUE THREAD

**Issue by genofire** [ffrgb/meshviewer#101]
This should be
- improve the performance 
- make bigger network more beautiful
- more handy for 

This feature was not reimplemented during my rewrite of d3 v4
https://github.com/ffrgb/meshviewer/commit/98f175d6a51a1b7f45fb720810a8a53cfe2aacf1

**Comment by genofire** [comment]
From @xf-:
IPhone has only a few KB localStorage, that crashed in other projects already

**Comment by genofire** [comment]
Is it possible to store it with Service worker (#100) on any kind?

**Comment by genofire** [comment]
use a faster startup of the graph

**Comment by xf-** [comment]
no - service-worker caches requests and stuff. LocalStorage is the way to go. maybe we need a detection

**Comment by genofire** [comment]
a detection of max space?

**Comment by genofire** [comment]
@xf- ??

**Comment by xf-** [comment]
i don't think this is still interesting. performance is good and save apply and update new node/links need also performance. We can maybe tweak a few parameters or add some new d3 functions for enhancement. PR is Welcome, but i don't see a clear task/issue.
(Reopen if you still think we need to add this)
