### ISSUE TITLE
Don't allow vpn links to be clicked in force graph

### ISSUE THREAD

**Issue by plumpudding** [ffrgb/meshviewer#116]
It's soo annoying to click a vpn link when you are trying to click a node.

**Comment by xf-** [comment]
I like clickable link, but maybe increase radius for node (not visible, only clickable)

**Comment by plumpudding** [comment]
imo vpn links are mostly uninteresting

especially the nodes hitboxes should be on top of the vpn links and all links should be on top of the vpn link

**Comment by xf-** [comment]
Links are behind nodes?
![image](https://cloud.githubusercontent.com/assets/1295633/24583425/5fc36ede-1749-11e7-8814-94e795deacf4.png)

**Comment by plumpudding** [comment]
I am talking about the hitbox. It happens to me that I click only a pixel away from a link and get the vpn link instead.

**Comment by xf-** [comment]
We can talk about adding a transparent "border".

**Comment by genofire** [comment]
Which kind of board, where nothing happen arround the node click array.

**Comment by xf-** [comment]
I like to click the links. I see a bad link and i want to inspect it.
GW without any link would look strange or a lot of links in list without functionality.
