### ISSUE TITLE
Remove fork info in about

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#127]
Currently we have a small info in about with links to fnord and hopglass, but i think it is not really useful. 
![image](https://cloud.githubusercontent.com/assets/1295633/25346074/e537790a-2916-11e7-8fac-5f5a2bd23f89.png)

Most librarys are updated or replaced/removed and most parts of code are changed (incl. grunt -> gulp, scss rewrite). Hopglass @plumpudding  want to switch to our repo as upstream and @tcatm isn't active anymore.

Keep info in README. No changes on Copyright info!

@genofire what do you think about the change?

I opened a issue for discussion.

**Comment by genofire** [comment]
The only important think in the about page are the licence and the name of these person which has start to developing. @tcatm - (which is still there above the part  you want to remove).

You got my okay

**Comment by xf-** [comment]
btw. @genofire - i looked around and looks like the copyright can only hold by one person and contributors can hold the copyright of parts. Also Copyright should include the first publishing date,
