### ISSUE TITLE
[BUG] [Draft] Load got to early warning on more than one CPU models

### ISSUE THREAD

**Issue by genofire** [ffrgb/meshviewer#13]
https://github.com/ffrgb/meshviewer/blob/bcd126464f505fa61d2390394ff1642761d734e2/lib/infobox/node.js#L152-L182

(I have see it, but could not found a example now ... -> Draft)

**Comment by xf-** [comment]
nproc - thx @genofire

**Comment by xf-** [comment]
https://github.com/ffrgb/meshviewer/compare/task/loadavgCpuCores?expand=1 should resolve this issue
