### ISSUE TITLE
Number of links in nodes tab is wrong

### ISSUE THREAD

**Issue by Suuush** [ffrgb/meshviewer#133]
Number of links in nodes tab is wrong, only seems to be the number of vpn links, neighbour nodes are not considered.

## Steps to Reproduce (for bugs)
1. Open https://map.bremen.freifunk.net/#/en/map
2. Goto nodes tab
3. Filter 'FF-Hagen-Cux-Kranich-Apotheke'
4. Number in column 'Links' is 0
5. Click on node name
6. Scroll down to 'Links'
7. Number of links is 6

**Comment by xf-** [comment]
I think the issue is source vs target - searches only in one direction

**Comment by genofire** [comment]
At the moment there are only VPN links from source in this column https://github.com/ffrgb/meshviewer/blob/ebc3ca4804e32257670243372acc9b8930bae30c/lib/main.js#L97

**Comment by Suuush** [comment]
... but it should be router links?

https://github.com/hopglass/hopglass/blob/master/lib/main.js#L172

**Comment by genofire** [comment]
You mean meshlinks :D
