### ISSUE TITLE
Forcegraph bugginess

### ISSUE THREAD

**Issue by plumpudding** [ffrgb/meshviewer#137]
## Steps to Reproduce (for bugs)
- Go to the graph view
- Click on a node
- Repeat until bugs appear

## Expected Behavior
The node that I clicked on should be focused and stay where it was. 

## Current Behavior
Sometimes the click will be registered at a different location, sometimes the node clicked on simply disappears. 
Video: https://pbb.lc/daten/meshviewer-bug-screencapture.mp4

## Your Environment
Chromium Mobile 60 build 3104 from May 18th (download: https://storage.googleapis.com/chromium-browser-snapshots/Android/472814/chrome-android.zip)
Android 7.1.2 (LineageOS)
Xiaomi Mi5 Pro

**Comment by genofire** [comment]
Do you mean, that the node jump to a other location?
(i see it you time in your capture)

**Comment by plumpudding** [comment]
There are multiple issues.
Sometimes the node just disappears from the screen and the (usually VPN-) link below is focused instead. (Only seen on Chrome/Chromium on Android until now)
Sometimes the node doesn't move but a different node gets focused.  (Only seen on Chrome/Chromium on Android until now)
Sometimes the right node gets focused but the node gets moved by a bit (also a problem on desktop, though not such a big problem)

**Comment by xf-** [comment]
#187 reduce force after init
