### ISSUE TITLE
Link Tooltip outside Viewport

### ISSUE THREAD

**Issue by belzebub40k** [ffrgb/meshviewer#138]
## Current Behavior

If less then the half distance of a link is visible in the viewport the tooltip is displayed outside the visible area.

## Possible Solution

Display tooltip under mouse pointer.

## Steps to Reproduce (for bugs)

1. Focus a node with a long distance link so that less then half of link distance is visible
    https://map.freifunk-mwu.de/#/de/map/c46e1f87b3ae
2. Zoom out while keeping the mouse pointer on the link

## Your Environment

* Version used: 3e63b6432e16658d802e9e923295a592fcfb7d83
* Browser Name and version: Firefox 53.0.3
* Operating System and version (desktop or mobile): Debian Stretch

**Comment by genofire** [comment]
I could not test it, at the moment ... hope it will solve it.
(A little Warning before: If it would not solve it and leaflet would not have a nice solution for thie problem - it is possible we have to ignore this issue. But i am hopefully, it will work.)

**Comment by belzebub40k** [comment]
Applied it to our instance for testing. Looks good on current version of Firefox and Chrome.

https://map.freifunk-mwu.de/#/de/map/c46e1f87b3ae

**Comment by genofire** [comment]
I see, top 👍 - should be solved with the PR 😄

**Comment by xf-** [comment]
I build it intentional without sticky option.
Cursor movement and multiple links it is hard to see current link.
- You follow a link and get a lot of repaints and flicker.
- You need to be more focused while using the meshviewer.

**Comment by xf-** [comment]
@belzebub40k @genofire i think the PR has no improvement - replacing one small problem with another one.
