### ISSUE TITLE
Error: Cannot read property 'mesh' of undefined

### ISSUE THREAD

**Issue by PowerPan** [ffrgb/meshviewer#141]
I want to use it for Freifunk Nordwest as well.
During my first test I get this error:

Cannot read property 'mesh' of undefined

For Data Collecting we are using Hopglass Server for the moment.

One of our data URLs:
https://map.ffnw.de/data/fri01/nodes.json
https://map.ffnw.de/data/fri01/graph.json

I don't know for the moment where the problem is.

Here is the build URL:

https://map.ffnw.de/rgb/build

**Comment by mweinelt** [comment]
Hopglass is no officially supported backend and therefore can break when the format changes. 

Use yanic (https://github.com/FreifunkBremen/yanic) instead and will be well.

See also https://meshviewer.gitbooks.io/documentation/content/supported-backends.html

**Comment by xf-** [comment]
Sry, but the info from @mweinelt is correct. We don't support other backend. Would make breaking changes much more complicated and also testing more time consuming. Hopglass plans to use us as upstream and apply necessary patches and wanted features.
With Yanic we have a lot of conversation and multiple developer's & community's involved in both projects. Regensburg & Bremen, also Darmstadt is active.
