### ISSUE TITLE
Define releases stuff

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#155]
- Version
  - Version number x.x.x
    - xx.X 
      - Bugfix for last release
      - Translation update
      - Minor library updates
    - x.X.x 
      - Possible style adjustments needed
      - Smaller code adjustments
    - X.x.x
      - Major changes code or frontend
      - Backend (yanic) updated needed
      - Large Library updates
  - Starting with v10.0.0 to avoid confusion
- How to release?
  - Tag release
  - Write Changelog
  - Try to provide Builds
  - Also provide a deug release/rebase
- Master is untouchable - no force pushes after a release

**Comment by mwarning** [comment]
Semantic Versioning might be a good idea: http://semver.org (e.g. 1.2.3)

The advantage of something like 2017.0.1 is that it indicates the year/month of the release.
But that information is not useful if software becomes stable and there is no need for a release for some time. People will look at the version and think that the version is outdated. my2cents..

**Comment by genofire** [comment]
i am for a Version with year in it 2017-1 would be the first.

**Comment by xf-** [comment]
I'm no big fan 2017.1 (second number month *buntu or freeze like arch?). We don't have regular updates.

We don't have the power to maintain 2 branches of code. 1 release like Firefox/Chromium is most similar process and a lot of major releases. (Personally i like KDE versions with 5 Codebase, .X can contain major changes .X Bugfixes and high numbers for alpha/beta/RC. But this is not our case)

Reasons for updates?
- New features
- Build environment fixes
- Security fixes
- Backend changes (yanic)

Most comminutes will update not so often - trying to make it easy as possible.

**Comment by genofire** [comment]
freeze - i just like, to see when as last stable version was released (is the project still active).

No there would be always just two branches (master with is tagged with versions and freezed and the developing branch) - if there is a reason of security fixes - then we should make a notification in the master README - that the stable version has a problem.

Backend (yanic) should always support every file output/version of meshviewer

**Comment by genofire** [comment]
It would be 10.0.0 :)
