### ISSUE TITLE
Add TQ for both directions

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#156]
## Expected Behavior

Information/indication about TQ from Both directions and not average.

## Current Behavior

Average

**Comment by xf-** [comment]
Drawing works
![screenshot_20170916_173327](https://user-images.githubusercontent.com/1295633/30513540-4720d426-9b05-11e7-9fc7-a7f97e2173b1.png)

Missing
Map Polyline

**Comment by xf-** [comment]
![image](https://user-images.githubusercontent.com/1295633/30515901-08012468-9b31-11e7-944b-80325b88fe61.png)
![image](https://user-images.githubusercontent.com/1295633/30515905-13451dfc-9b31-11e7-8c3d-382f4b403649.png)
![image](https://user-images.githubusercontent.com/1295633/30515908-2781dada-9b31-11e7-9ca2-0d48252ec867.png)
(Data is not real - i have a generator to set number of wanted nodes and provide more edge caes)

Polyline on the map is not possible. Maybe via canvas or svg direct or via plugin. I don't think the overhead is necessary - the values exist on hover - in infobox and in graph.

**Comment by rotanid** [comment]
did you close this issue because it will be pushed soon or because you stumpled upon unsolvable problems?

which value is drawn, the smaller one, the average or the maximum? i'd say the smaller one would make the most sense...

**Comment by xf-** [comment]
Is finished - pushed soon. Correctly no supported backend. Map has average like before and hover shows both values
