### ISSUE TITLE
German translation error

### ISSUE THREAD

**Issue by dersch81** [ffrgb/meshviewer#161]
Hi, I just want to tell you a small error in the german translation:

![meshviewer language fail](https://user-images.githubusercontent.com/13754891/31352900-c34d99d4-ad30-11e7-8189-e61fcfa66d73.jpg)

**Comment by xf-** [comment]
durchschnittliche Belastung ist zulang

**Comment by blocktrron** [comment]
On the Gluon statuspage, it is translated with "Systemlast".

**Comment by xf-** [comment]
It is a average in last minute. A lot of terms are english like "Auto-Update", "Gateway". I used Wikipedia and sounded like "Load average" is common enough and not traslated https://de.wikipedia.org/wiki/Load

**Comment by dersch81** [comment]
I think "Load average" is quite strange within a full translation. "Auto-Update" & "Gateway" is fine because we say it in the same way. But "Load average" jumps in your eye and says WRONG! Normally you would never speak it out in german. :D 

So as @blocktrron said "Systemlast" is pretty fine and not 100 % wrong.
