### ISSUE TITLE
Order of firmware version in statistics

### ISSUE THREAD

**Issue by mmalte** [ffrgb/meshviewer#170]
The order of Firmware Version in the statistics tab is not the same as the one used by the gluon autoupdater.

It would be extremely helpful to use the same order, to help to find nodes which are not up to date. We use the ~ for experimental Version, see attached Screenshots:

correct order in Hopglass:
![image](https://user-images.githubusercontent.com/6890998/31856642-5aadd32c-b6c6-11e7-9294-dcb97af4b572.png)

order in current meshviewer, ~ seems to be a newer version than -:
![image](https://user-images.githubusercontent.com/6890998/31856648-819af992-b6c6-11e7-818d-5a411c9c4053.png)

Live Versions:
https://map.aachen.freifunk.net/
http://map.freifunk-aachen.de/new/#/de/map

**Comment by xf-** [comment]
We don't plan to add a complex sort/libary. A improvement could be 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

This would improve sort for  1 < 10.

```diff
diff --git a/lib/proportions.js b/lib/proportions.js
index 0c4eb15..310b93f 100644
--- a/lib/proportions.js
+++ b/lib/proportions.js
@@ -132,13 +132,7 @@ define(['d3-interpolate', 'snabbdom', 'filters/genericnode', 'helper'],
           return b[1] - a[1];
         }));
         fwTable = fillTable('node.firmware', fwTable, fwDict.sort(function (a, b) {
-          if (b[0] < a[0]) {
-            return -1;
-          }
-          if (b[0] > a[0]) {
-            return 1;
-          }
-          return 0;
+          return a[0].localeCompare(b[0], 'co', { numeric: true });
         }));
         hwTable = fillTable('node.hardware', hwTable, hwDict.sort(function (a, b) {
           return b[1] - a[1];
```

**Comment by mmalte** [comment]
Please don't use the count to sort this value and make things even worse, this stat is extremly helpful to find nodes which are not up to date. Especially with some filters like 'autoupdate branch' enabled.

The gluon autoupdate order is the same that is used by debian/ubuntu. For example the linux command 'sort' only needs to be used with '-V' to provide this order.

**Comment by xf-** [comment]
I think JavaScript has no sort to change sorting order of ascii chars like ~ and -

**Comment by rubo77** [comment]
https://stackoverflow.com/a/40201629/1069083

A short search for " javascript sort debian version number"

**Comment by xf-** [comment]
@rubo77  doted version works with local compare and numeric option. The problem is ~ vs -. A possible hacky fix would be to replace ~ or - with a char in correct order.

**Comment by yayachiken** [comment]
Since we really would appreciate this feature, I went digging and looked for the point of divergence because this stuff worked in the old meshviewer..

I found that the working version comparison was removed by you in commit 685e25a38.
Do you remember the rationale for removing this?

Because we think this feature is really useful for our monitoring, but Hopglass grows more and more unusable in our domain due to performance issues, it is likely eventually somebody in our community would volunteer to bring the old implementation up to higher standards.

To do that we would need to know what the old grievances were so we can fix the old code up to be able to be accepted. Obviously, if **any** PR on this issue were to be rejected, we would not bother doing senseless work, so that would be good to know as well.

**Comment by xf-** [comment]
I removed it because we didn't use it and a simple sort had the same result in our case. Like i wrote a small simple solution is welcome. A complete 68 lines of different compares isn't worth it.

**Comment by mmalte** [comment]
It is possible to do it with less code:

https://codegolf.stackexchange.com/questions/33003/golfed-sort-by-debian-version-number

**Comment by rubo77** [comment]
I wonder, why you bother about 60 lines?

The mv is downloading the nodes.Json every minute, which is 500 k on large domains each minute

**Comment by xf-** [comment]
Code contains a lot of expensive" operations like regex in while loop * in sort loop (aachen 59 runs + vercomp). Runs on every filter operation like node filter or click on other stats. Also updates every minute.

**Comment by rubo77** [comment]
Ok. So the problem is not the code length but the CPU usage

**Comment by xf-** [comment]
It is also in critical path initially. after loading js the json will be loaded and needs more cpu time. Maps get bigger and bigger and i think it should work on low-end devices.

**Comment by rubo77** [comment]
Maybe simply replace ~ with`0.` before sorting?

**Comment by jannic** [comment]
Is it really a performance issue to sort ~20 strings with a little bit more complex function?
If I don't misunderstand the code, the sort is done on a list of the firmware versions, not on the full list of nodes. In Aachen we have 16 different firmware versions on ~2000 nodes. I guess other communities don't have much more distinct versions.
Yes, maybe the regular expressions in the old code could be optimized away. But I doubt the performance difference is noticeable. Perhaps not even measurable, in the context of displaying 2000 nodes on a map.

**Comment by xf-** [comment]
It is slower - 2-30 times (deeding on browser firefox/chromium and loops). Multiple first hits are 10-30 times slower. Loops (1000) 2 times slower in chromium and 5 times in firefox (not normal use case, but more consistent results). (On full CPU power, throttling usually will prove the result it is worse. Like you wrote 2k nodes needs already a lot of power. Every saving helps...)

I tried to find a nice library like https://github.com/omichelsen/compare-versions but found non. I really don't want to maintain and ship the library.

**Comment by xf-** [comment]
won't compile and compile stuff in JS is overkill (dependency's)
https://github.com/diorahman/vercmp

**Comment by xf-** [comment]
Works if you adjust the module loading. I won't create a PR. If somebody wants to, go for it...
https://www.npmjs.com/package/deb-version-compare

**Comment by genofire** [comment]
Okay start creating some tests:

https://github.com/omichelsen/compare-versions <- cound not handle `~`
https://github.com/diorahman/vercmp <- binary not possible in browser (developed for nodejs on a server)

My tests are written here in a gist (https://gist.github.com/genofire/dcaa858d39407e9649c5aea91d39078d): 

https://github.com/ffrgb/meshviewer/commit/685e25a38f2acb4d8a03c327392f8b6e75bf5227: 77ms with current Tests
https://github.com/sdumetz/node-deb-version-compare/blob/master/lib/Version.js <- not tested yet

I will change the test this week to use a real list of version:
found files with valide version: https://pastebin.com/GuiUDQ6x and https://pastebin.com/rh9KrShX.
and create the last test.

could anyone post new js debian version compare implementations?
