### ISSUE TITLE
Incomplete display of numbers in statistics

### ISSUE THREAD

**Issue by mmalte** [ffrgb/meshviewer#189]
I've there is only a small percentage of nodes with a certain attribute, but the absolute number already got 3 digits, the last digit is no longer shown.

Is this example it seems like there are only 10 nodes with the beta branch autoupdater:
![image](https://user-images.githubusercontent.com/6890998/32177996-e67cf93e-bd8b-11e7-86c5-9b6d248c124a.png)

In reallity there are 102, as you see when only these nodes are selected:
![image](https://user-images.githubusercontent.com/6890998/32178089-2c4155e6-bd8c-11e7-8a2c-4e758a9ab26f.png)

Same thing happens with the firmware versions and the online nodes.

Since it works fine with two digits, I am under the impression that there is am minimum size of the bars.

**Comment by xf-** [comment]
I saw your edge case. The problem is 3 digest and only a few procent needs a lot of nodes (> 2k in your case). Night mode fixes it with another background color. I will find something. The length of bars should be correct and not depending on value.

**Comment by xf-** [comment]
@mmalte can you test this
```patch.patch
diff --git a/lib/proportions.js b/lib/proportions.js
index 260a761..1a54987 100644
--- a/lib/proportions.js
+++ b/lib/proportions.js
@@ -64,9 +64,8 @@ define(['d3-interpolate', 'snabbdom', 'filters/genericnode', 'helper'],
           var th = V.h('th', a);
           var td = V.h('td', V.h('span', {
             style: {
-              width: Math.round(v * 100) + '%',
-              backgroundColor: scale(v),
-              color: 'white'
+              width: 'calc(25px + ' + Math.round(v * 90) + '%)',
+              backgroundColor: scale(v)
             }
           }, d[1].toFixed(0)));
```

**Comment by mmalte** [comment]
Thank you, I am able to confirm that this fixed the issue:

![image](https://user-images.githubusercontent.com/6890998/32226970-442c3a86-be4a-11e7-9445-97b1700ecacb.png)

I only did cerry-pick daf0a979c67c783b5f5726f13512226416af2a82 to the development branch.
