### ISSUE TITLE
Vectoring MAP

### ISSUE THREAD

**Issue by genofire** [ffrgb/meshviewer#19]
Ab Februar würde ich mich draufschmeißen ... hier schon mal Ansätze :)

https://github.com/mapbox/mapbox-gl-leaflet

https://openmaptiles.org/styles/#osm-bright

http://osm-liberty.lukasmartinelli.ch/#17.89/53.07194/8.79055

**Comment by xf-** [comment]
I'm open to test it. Disadvantage is "Slow"-Devices need to render the tiles with good performance.

Different Plugins exit. mapbox/mapbox-gl-leaflet has a note it is experimental
http://leafletjs.com/plugins.html#vector-tiles

First step we need leaflet v1

**Comment by xf-** [comment]
https://github.com/plumpudding/hopglass/issues/72

**Comment by plumpudding** [comment]
In my experience performance on mobile devices gets worse obviously while data usage is lower. I would rather use map tiles on my mobile devices because they perform better.

**Comment by xf-** [comment]
i think we need to replace leaflet. other systems are much faster and also would be great for zoom and service worker.

**Comment by SimJoSt** [comment]
With other systems are there more, other or combined options in contrast to tiles and vectors?

**Comment by xf-** [comment]
I will close this issue for now. Overlays for leaflet are inactive (maybe leaflet will add native support someday) and work vs. benefits isn't worth it. (Clean) PRs are always welcome.
