### ISSUE TITLE
Forcegraph link to link

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#192]
## Expected Behavior

link with id-id should always resolves

## Current Behavior

fails sometimes.

## Possible Solution

maybe source/target switched?

**Comment by genofire** [comment]
whats missing? the nodeid or the node with the given nodeid in a link?

**Comment by genofire** [comment]
Hoppely fixed in `meshviewer.json` output: yanic - 
https://github.com/FreifunkBremen/yanic/commit/fdb0083a86b1750136a16f1f5c066bd4d42053c1

**Comment by genofire** [comment]
We have to write it somewhere down at the `meshviewer.json` definition.
So other backend would not create the same issue again.

**Comment by xf-** [comment]
+1
