### ISSUE TITLE
Invalid stats of client

### ISSUE THREAD

**Issue by genofire** [ffrgb/meshviewer#20]
Something is wrong with the count of stats in the sidebar

[respond-collector](https://map.ffhb.de/): 711 Knoten (641 online, 7 neu, 41 verschwunden)
[Alfred](https://ffhb.de/meshviewer/): 716 Knoten (655 online, 7 neu, 32 verschwunden)

**Comment by xf-** [comment]
I don't think this is a meshviewer issue.

https://ffhb.de/meshviewer/#!v:m;n:e8de2758fafc missing on https://ffhb.de/meshviewer/#!v:m;n:e8de2758fafc

I used firefox (nightyly) new json-viewer and copied the object-list, sorted both. Diff afterwards showed missing objects (MAC addresses).

**Comment by genofire** [comment]
yes, there are different nodes visible, that my fold (or gluon that respondd crashed on this release) - that is not the problem.

The Problem is that the summes not correct:

respond-collector: 711 Knoten (641 online, 7 neu, 41 verschwunden = 689)
711 != 689 (641 + 7 + 41)

Alfred: 716 Knoten (655 online, 7 neu, 32 verschwunden = 694)
716 != 694 (655 + 7+ 32)


there is both a difference of 22 nodes.
(711 - 689 = 22 or 716 - 694 = 22)

**Comment by genofire** [comment]
okay but `x offline > maxAge` should also called offline or sum shound not contain `x offline > maxAge`

**Comment by xf-** [comment]
resolved via 2a5efa08757bb27b0eaf97602448b32ab03f76da
