### ISSUE TITLE
create config.json.example and add config.json to .gitignore

### ISSUE THREAD

**Issue by rubo77** [ffrgb/meshviewer#210]
## Expected Behavior
The config file should not change the git head

## Current Behavior
the config file is changing the content of the git repository

## Possible Solution
create an extra fie `config.json.example``that is part of the git repo and add `config.json` to `.gitignore` 

## Context
I want to be able to just use `git pull` on my live server to get the latest changes

**Comment by xf-** [comment]
Use `git pull --rebase`
