### ISSUE TITLE
No node details

### ISSUE THREAD

**Issue by Vogelbecker** [ffrgb/meshviewer#216]
Hi

i want to replace hopglass with meshviewer. 
I installed YANIC and its working.

I set up meshviewer. The nodes are visible on the map. But as i click on a node, the details are just showing the node's hostname.
If i use the datasource from the default config (https://regensburg.freifunk.net/data/) the node details are fine.
Any ideas?
My installation is here: http://vpn1.freifunk-einbeck.de/meshviewer

PS.: Who do i have to ask to use the FFrgb maptiles server?

**Comment by xf-** [comment]
I think yanic isn't up2date still provides network) and we moved the information. Sry about that, we are developing new format and that was a breaking change. We will provide a stable/master soon to avoid those issues.

tiles
Write me an email or freifunk regensburg and i will answer it.

**Comment by genofire** [comment]
Jep, yanic and meshviewer has change - his format for IP-Address and MAC.
https://github.com/FreifunkBremen/yanic/pull/92
meshviewer: https://github.com/ffrgb/meshviewer/pull/209

```
TypeError: i is undefined
Stack-Trace:
o.showIPs@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:260092
c.render/<@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:262246
c.render@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:262162
h.gotoNode@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:265483
i/<@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:62767
i@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:62745
@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:63359
resolve/</<@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:58923
h@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:56536
resolve/<@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:58878
h@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:56536
resolve@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:58865
@http://vpn1.freifunk-einbeck.de/meshviewer/app.js?t=1510052317820:42:343644
  app.js:42:343981
```

**Comment by Vogelbecker** [comment]
Ok, Thanks for the quick reply.
If you need some additional enviroment for testing, please let me know.

I will try it again, when a new version will be avalible

**Comment by xf-** [comment]
Update yanic im master and it should work

**Comment by Vogelbecker** [comment]
Thanks. It is woking now!

**Comment by genofire** [comment]
I add your yanic output in my playground: https://github.com/genofire/meshviewer-collector/blob/master/config.toml 👍
