### ISSUE TITLE
add prominent hint to use gluon-radvd-filter

### ISSUE THREAD

**Issue by rubo77** [ffrgb/meshviewer#220]
There should be a prominent link in the [Dependencies](https://meshviewer.gitbooks.io/documentation/content/build_install.html#dependencies) to the radvd package (official or not) that reveals the **secret knowledge**, that you will only see the selected IP 6 gateway in the details of a node if you have added that package to your firmware.

**Comment by xf-** [comment]
This is far away from building the firmware. Maybe in yanic or in gluon as optional dependency with advantage.
