### ISSUE TITLE
Client count on offline nodes

### ISSUE THREAD

**Issue by Vogelbecker** [ffrgb/meshviewer#231]
Hi there,

i noticed that meshviewer shows a number of clinets on nodes which are currently offline.
![grafik](https://user-images.githubusercontent.com/5623420/33483063-3ef779c6-d69c-11e7-9bcb-9266bebb3f91.png)

Shouldn't there be 0 clients?

**Comment by xf-** [comment]
yes, @genofire yanic or meshviewer?

**Comment by genofire** [comment]
I do not know (https://github.com/FreifunkBremen/yanic/issues/83) sometimes i think it is nice to know the last state.

if respondd crashed because a huge load or something ... so i like to keep memory and client usage in the map.

**Comment by xf-** [comment]
Maybe interesting in last 15 Minutes, afterwards a look in stats graph is more helpful. - i would set client count to 0

**Comment by mweinelt** [comment]
@genofire TSDB should be there if you want to know a last state.

**Comment by genofire** [comment]
What's happen with `load` and `memory_usage` and so on?

**Comment by mweinelt** [comment]
Those are per device metrics, client count is however accumulated into a total sum that is off by the sum of clients shown on offline nodes.

**Comment by xf-** [comment]
Last value is ok for me. Big difference is clients are global. Used in counts and lists. Load and memory are are shown with detail view.

**Comment by xf-** [comment]
i wrote with @genofire and we decided, it should be changed in yanic
