### ISSUE TITLE
meshviewer shows same routers mopre than 1 time

### ISSUE THREAD

**Issue by sap-dev** [ffrgb/meshviewer#237]
Hi there,

the FFNW have split there network into multiple L2 networks.

When a router connect to more than 1 server, it push his data in to more than one meshviewer.json
On Screenshot you can see the problem - on one meshviewer.json is online, on other one its offline. 

YANIC delete this nodes after 1 day - it is here a workaround for this problem, when mac >1 exist? The Map count this router as 2 or more...

Thanks.

**Comment by xf-** [comment]
no screenshot

**Comment by sap-dev** [comment]
See here:
https://picload.org/view/ddddwwiw/unbenannt.png.html
https://picload.org/view/ddddwwpa/unbenannt.png.html

**Comment by sap-dev** [comment]
See here:
https://picload.org/view/ddddwwiw/unbenannt.png.html
https://picload.org/view/ddddwwpa/unbenannt.png.html

In Live:
you can Search for Brake-Rathaus Router

**Comment by xf-** [comment]
you can upload images to GitHub via ctrl+v or drag and drop

**Comment by sap-dev** [comment]
Dont work here - i dont know, whats wrong

**Comment by xf-** [comment]
Meshviewer is for us primarily a visualisation tool and not modifying input data. For https://multi.meshviewer.org/ we use https://github.com/genofire/meshviewer-collector and could be a solution.

**Comment by sap-dev** [comment]
Ye, we make it with this. thanks.
