### ISSUE TITLE
Add domain code

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#243]
Gluon will support domain code.
Ask @mweinelt for details

**Comment by genofire** [comment]
@mweinelt -> kann dafür site code fallen?
(damit sollten die meisten communities ja nicht mehr mehrere sites laufen lassen)

**Comment by mweinelt** [comment]
Würde @lemoer und @kb-light gerne als Joker befragen.

**Comment by genofire** [comment]
Oder reicht ggf. auch ein einfacher switch in der config (oder filter in yanic, der den domain_code auf site_code umschreibt?)

**Comment by lemoer** [comment]
Es ist immer noch möglich unterschiedliche site-repo-Zweige im Netz zu haben. In unserer Community gibt es Nutzer, die sich eigene Firmware (mit teils abweichender site) bauen.

**Comment by genofire** [comment]
Doch eine domain gehört immer zu eine site?
Ist also in einer Baumstruktur die site immer der parent einer domain?

**Comment by lemoer** [comment]
Ja. Aber wenn ich die Frage richtig verstanden habe, dann ging es ja darum den "site_code" nicht mehr zu exposen, oder nicht?

**Comment by genofire** [comment]
daher die frage, ob man `site_code` durch `domain_code` ersetzen kann.

**Comment by mweinelt** [comment]
Multidomain ist optional. Daher sollte vermutlich beides exposed werden falls vorhanden.

**Comment by lemoer** [comment]
Außerdem ist `site_code` eventuell auch in Multidomain-Umgebungen immer noch sinnvoll, wenn man bspw. Firmwares mit eingebackenen SSH-Keys, ... hat.

**Comment by genofire** [comment]
Ist eine `site_code` nun ein parent der `domain_code` in der Baumstruktur?

**Comment by mweinelt** [comment]
Ja

**Comment by xf-** [comment]
wenn wir das ummappen sollte es passen @mweinelt . Also yanic  nimmt den domain code falls vorhanden statt site_code

**Comment by xf-** [comment]
kann aktuell nicht geloest werden.

**Comment by bobcanthelpyou** [comment]
@xf-  Warum kann es aktuell nicht gelöst werden?

**Comment by xf-** [comment]
Da wir aktuell noch kein value im meshviewer.json haben. Das liegt daran das alles etwas chaos ist:

Es gab schon viele aussagen zu domain_code usw. (einige nicht mehr aktuell):
- domain_code löst site_code ab (site_code ist legacy)
- domain_code Ist Segmentierung unter site_code
- domain_code hat nichts mit site_code zu tun
- Initial kam daher die Idee die zusammen zusetzten also sitecode / domain_code oder anderer trenner... Dann hieß es nein, sollen beide getrennt verfügbar sein. Für beide einen Filter verfügbar zu haben verwirrt in meinen Augen nur, da man vermutlich erst in Gluon Doku gehen muss um als Laie Gateways, site_code und domian_code unterschied zu sehen (kommt auch immer etwas auf die Benennung der jeweiligen Community an).

**Comment by rotanid** [comment]
dort ist es dokumentiert:
https://gluon.readthedocs.io/en/v2018.1.x/features/multidomain.html

Zusammenfassung:

- `site_code` bleibt wie bisher bestehen
    - normalerweise einer pro Community (manche Communities mit mehreren)
    - site_name ist human-friendly Titel dazu
- sofern die Community GLUON_MULTIDOMAIN aktiviert
    - `domain_code` mindestens 1, in der Regel mehrfach pro site
    - human-friendly Bezeichnung zu jedem domain_code
    - domain_code unique pro site (nicht global)
