### ISSUE TITLE
Post data to open wifi map

### ISSUE THREAD

**Issue by niccokunzmann** [ffrgb/meshviewer#247]
## Expected Behavior

I would like to see all meshviewer nodes on the openwifimap.

## Current Behavior

https://openwifimap.net/#map?bbox=50.39451208023374,7.338867187500001,53.014783245859235,16.5673828125
to me is seems like we are missing out on all the meshviewer available nodes

## Possible Solution

- a repository running a cron job which fetches the data from mesh viewers and posts it to open wifi map
  (works with all running versions) https://github.com/niccokunzmann/meshviewer-to-openwifimap
- an extension of the mesh viewer which posts the data automatically (works with all updated versions)

## Context

I think, the openwifimap is used as an example map to gather all important-data.
I am from Potsdam.

**Comment by xf-** [comment]
Hi, i don't know if you are on right place. yanic is the Backend (supports multiple formats) including output for https://www.freifunk-karte.de/ .

**Comment by niccokunzmann** [comment]
I found yanic: https://github.com/ffrgb/yanic
Where can I get in contact with https://www.freifunk-karte.de/ ? E.g. Weimarnetz is missing. I can not find the source code.

**Comment by genofire** [comment]
https://github.com/FreifunkBremen/yanic pls - upstream ;)

nodelist.json / freifunk-karte.de works in stemps
1. https://github.com/freifunk/directory.api.freifunk.net/blob/master/directory.json
2. iterate over every community: https://freifunk.net/api-generator/ -> over ffapi.json
 -> nodeMaps.mapType ...
3. save all this json

but i do not know there the repo of software for it is, ask @StilgarBF.
