### ISSUE TITLE
Tiles missing with offline service worker

### ISSUE THREAD

**Issue by mweinelt** [ffrgb/meshviewer#252]
Since service workers are integrated the tiles only load after force-reloading meshviewer. Else the tiles are served from the service worker, but they are 0 Bytes in size. The map layer stays gray.

## Expected Behavior

The tiles should load and the map should be visible.

## Current Behavior

Map stays gray, tiles don't appear unless force-reload.

## Steps to Reproduce (for bugs)

1. Configure Webserver to use CSP as seen in environment
> content-security-policy: default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src *; font-src 'self'; worker-src 'self'; connect-src https://tiles.darmstadt.freifunk.net/ https://stats.darmstadt.freifunk.net/ https://nominatim.openstreetmap.org/ 'self'; frame-ancestors *; child-src 'self'; block-all-mixed-content;
2. Load meshviewer from it
3. Notice missing tile behaviour

## Your Environment
```
% curl -I https://meshviewer.darmstadt.freifunk.net
HTTP/2 200                                                     
server: nginx/1.10.3
date: Thu, 26 Apr 2018 20:46:39 GMT
content-type: text/html
content-length: 34908
last-modified: Fri, 20 Apr 2018 14:09:15 GMT
etag: "5ad9f48b-885c"
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
referrer-policy: no-referrer-when-downgrade
content-security-policy: default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src *; font-src 'self'; worker-src 'self'; connect-src https://tiles.darmstadt.freifunk.net/ https://stats.darmstadt.freifunk.net/ https://nominatim.openstreetmap.org/ 'self'; frame-ancestors *; child-src 'self'; block-all-mixed-content;
referrer-policy: no-referrer-when-downgrade
x-frame-options: ALLOWALL
accept-ranges: bytes
```

* Version used: v10.0.0-17-g300a732
* Browser Name and version: Chromium 64, Firefox 61
* Operating System and version (desktop or mobile): Both
* Link to your project: https://meshviewer.darmstadt.freifunk.net/#/en/map

**Comment by xf-** [comment]
was a cache issue
