### ISSUE TITLE
Gateway count is irritating in multidomain setups

### ISSUE THREAD

**Issue by mweinelt** [ffrgb/meshviewer#253]
We currently run 6 gateways, serving 19 domains, which makes meshviewer show 114 gateways, although they run on the same gateways.

> 1059 nodes, including 874 nodes online with 2345 clients on 114 gateways

I have no simple idea how we can resolve this, except maybe divide by domains? this of course has other issues...

https://meshviewer.darmstadt.freifunk.net/#/en/map

**Comment by genofire** [comment]
Do you run multiple mesh-announce instance? (with multiple nodeid)

**Comment by mweinelt** [comment]
I'm currently running https://github.com/ffnord/mesh-announce/pull/23 to spawn one respondd instance per mesh domain.

**Comment by xf-** [comment]
@mweinelt is this an meshviewer issue or an issue of yanic, meshviewer-collector or mesh-announce to filter/ provide correct information or something else? Meshviewer only provides the view and counts all nodes with flag gateway true.
At some point we use nodeID as index and thats why Stats offline + online has an offset of ~120 nodes.
I think in multi the meshviewer-collector filters duplicate nodes.

**Comment by xf-** [comment]
I will close this for now. Nodes all use unique IDs and multiple PRs are open mesh-announce to prevent or improve the situation. We are only a visualization tool. Please correct me if i missed something.
