### ISSUE TITLE
README.md: All links to 'meshviewer.org' are broken

### ISSUE THREAD

**Issue by oszilloskop** [ffrgb/meshviewer#254]
I was just going to install the meshviewer as a test. But unfortunately I can't find the installation instructions which are probably linked in the README.md.

All links to [meshviewer.org](https://meshviewer.org/) are broken (within the Github project, as well as in the README.md file).

**Comment by xf-** [comment]
We know. Was hosted @ netlify via git deployment. Put it down because of DSGVO. I will move it to one of my servers.

**Comment by oszilloskop** [comment]
Could you please place/upload the latest Installation-PDF inside a comment of this issue?
Github will then serve it until as long as you need for transfer it to an other of your servers.

**Comment by rubo77** [comment]
You can view the old readme with instructions: https://github.com/ffrgb/meshviewer/blob/426d52d0d6861cc00ae8f8457c7c37b8e8a6080b/README.md

**Comment by rubo77** [comment]
You can use the "Download PDF" link on https://legacy.gitbook.com/book/meshviewer/documentation/details

**Comment by xf-** [comment]
@rubo77 docu is online @github
https://github.com/ffrgb/meshviewer-doc
