### ISSUE TITLE
Change wording of "Disappeared nodes"

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#255]
## Expected Behavior

Something more offline or Disappeared

## Current Behavior

Term: Disappeared nodes

## Possible Solution

Change wording to "Currently Offline/Disappeared nodes" or something similar

## Context

New nodes only consists of new nodes (or long enough offline for yanic) and offline includes closed stores (power supply on a timer), event locations and list is long. Also stuff like issues with provider, gateway issues...

**Please comment or vote your opinion**

**Comment by xf-** [comment]
tried some changes, but to long for a single line. Maybe some other way to make offline less "shocking" 10 new 30 offline.

**Comment by mweinelt** [comment]
vanished/verschwunden?
