### ISSUE TITLE
Router die loops kreieren vollautomatisch verpetzen

### ISSUE THREAD

**Issue by rubo77** [ffrgb/meshviewer#258]
https://forum.freifunk.net/t/layer2-loop-aufspueren-innerhalb-eines-batman-und-tunneldigger-l2tp-netzes/19115/13?u=rubo77

## Is your feature request related to a problem? Please describe.
loops can severely damage the whole network

## Describe the solution you'd like
mark all nodes on the map that are creating such loops

**Comment by xf-** [comment]
I think meshviewer is the wrong place. Meshviewer is a visualization and no monitoring tool. For Example we only use snapshot of current state in a json and have no longer history available. You can add alerts in grafana http://docs.grafana.org/alerting/rules/
