### ISSUE TITLE
fullscreen mode problems

### ISSUE THREAD

**Issue by Grotax** [ffrgb/meshviewer#264]
## Expected Behavior
Fullscreen button toggles fullscreen mode on and off

## Current Behavior
Linux, Chromium (68):
If you are already in fullscreen mode the button does nothing

Linux, Firefox 61:
It doesn't work at all, TypeError: n is undefined

**Comment by xf-** [comment]
any link to test?
i tested it in local gulp

**Comment by xf-** [comment]
fixed
