### ISSUE TITLE
Possible XSS issue

### ISSUE THREAD

**Issue by anoymouserver** [ffrgb/meshviewer#265]
If the node name has an xml-like tag in its name, the tooltip on the map seems to render it, since the value is not escaped with `&lt;` and `&gt;`.
In the worst case you could insert a `<script>` into the website or just break the layout.

Example at our map: [`<name>-Space WR842N - Freifunk Gera-Greiz`](https://www.freifunk-gera-greiz.de/meshviewer/#/de/map/ec086b56c990)

**Comment by xf-** [comment]
I can't find a way to inject HTML or script into website. (I tested it before - the Library that handles HTML nodes escapes it.) You can load the Meshviewer, run it via gulp serve and change dataPath to ./ and store a meshviewer.json under build and modify it.

![image](https://user-images.githubusercontent.com/1295633/43722559-cf9182c6-9995-11e8-920b-8d0fe7c0697c.png)
![image](https://user-images.githubusercontent.com/1295633/43722584-dc822864-9995-11e8-8c84-693f1592d56a.png)
![image](https://user-images.githubusercontent.com/1295633/43722604-ec985674-9995-11e8-8760-1f711d6d341b.png)

**Comment by xf-** [comment]
@anoymouserver  If i add an escape, it will be double encoded.

**Comment by anoymouserver** [comment]
> Looks like the tooltip in map isn't escaped. (Hopglass has the same issue with a different tooltip)

Yes I only meant the tooltip, everything else is fine. And yes, Hopglass has the same issue, but currently it isn't maintained.

**Comment by xf-** [comment]
THX @anoymouserver for the report and it is fixed in 8bf3498 :) Everything else runs trough libarys.
