### ISSUE TITLE
rename config.js to config.js.example

### ISSUE THREAD

**Issue by rubo77** [ffrgb/meshviewer#267]
## Expected Behavior
If you do not provide a `config.js` in your folder, all defaults should be used

## Current Behavior
the program crashes

## Possible Solution
1. add all values from config.js to config.default.js 
2. rename config.js to config.js.example.
3. add `config.js` to `.gitignore`.

This will ensure, that all needed values are always present and local settings for your setup are not overwritten when doing a `git pull`. Also this is the standard procedure on most software projects.

**Comment by xf-** [comment]
No plan to change it. Next complains about exception without renaming the file.
The goal was to provide a running version and also this is productive meshviewer of ffrgb and all config is available.Next one complains about not up2date documentation or example.

We commit our config and rebase on develop. ((You could a merge with unnecessary merge commits.) Changes on config are not common and most not community specific settings are in config.default.js and can be overwritten in config.js.
