### ISSUE TITLE
custom.scss causes build failure

### ISSUE THREAD

**Issue by mwarning** [ffrgb/meshviewer#269]
Using scss/custom/custom.scss causes build error.
Build steps:
```
get clone  https://github.com/ffrgb/meshviewer.git
cd meshviewer
yarn
#create scss/custom/custom.scss
gulp
```
custom.scss content:
```
// Hide gluon uci command field in location picker
box-uci { display: none; }

// Hide gateway field
table.attributes tr:last-of-type { display: none; }

// Hide section "gateway next hop"
.gateway { display : none; }

// Hide 2.4 GHz / 5.0 GHz section
.legend-24ghz { display : none; }
.legend-5ghz { display : none; }
.legend-other { display : none; }
```

The error:
```
$ gulp
[22:20:37] Using gulpfile ~/tmp/meshviewer/gulpfile.js
[22:20:37] Starting 'default'...
[22:20:37] Starting 'eslint'...
[22:20:37] Starting 'sasslint'...
[22:20:39] Finished 'sasslint' after 1.76 s
[22:20:40] Finished 'eslint' after 2.43 s
[22:20:40] Starting 'copy'...
[22:20:40] Starting 'javascript'...
[22:20:40] Starting 'sass'...
[22:20:40] Starting 'jsonMinify'...
[22:20:40] Optimizing app.js
[22:20:47] Finished 'sass' after 7.44 s
[22:20:47] Finished 'javascript' after 7.44 s
[22:20:47] Finished 'jsonMinify' after 7.46 s
[22:20:47] Finished 'copy' after 7.48 s
[22:20:47] Starting 'html'...
[22:20:48] 'html' errored after 242 ms
[22:20:48] Error in plugin 'gulp-inline-source'
Message:
    ENOENT: no such file or directory, open '/home/mwarning/tmp/meshviewer/build/main.css'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: /home/mwarning/tmp/meshviewer/build/main.css
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by xf-** [comment]
The problem is incorrect naming and the duplicate.

scss/custom/_custom.scss exists
You added scss/custom/custom.scss
-> Both files can be included with @include custom/custom and in your case both files exists and nothing happens at all.

Files without underscore will generate an extra css file.

About the linter - it will complain, but you can ignore it or add an disable line/block....

**Comment by mwarning** [comment]
renaming `scss/custom/custom.scss` to `scss/custom/custom.scss` fixed the problem, but this is kinda odd.

**Comment by xf-** [comment]
@mwarning more or less logical - you load 2 files with same name at once. if you delete _custom.scss it should work as well. We ship the _custom.css file to avoid touching the code and also inside the file is a small description.

**Comment by mwarning** [comment]
_custom.scss and custom.scss are different file names from my perspective.

**Comment by xf-** [comment]
yes, but in scss both are @import custom:
_custom.scss - create no custom.css -> _  (will be imported in your xy.scss)
custom.scss - create a custom.css (will be imported in your xy.scss)
https://sass-lang.com/guide#topic-5

This is interesting if you build multiple files.
