### ISSUE TITLE
Open statistics in target="_blank"

### ISSUE THREAD

**Issue by rubo77** [ffrgb/meshviewer#273]
## Is your feature request related to a problem? Please describe.
You are on a slow connection where the data needs minutes to be loaded. When you click on a statistics graph, and forget to use the right mousebutton to "open in new tab" you loose the meshviewer page and have to load it again when you go back.

## Describe the solution you'd like
the option 

    target="_blank"
on all links that lead away from the mehsviewer

**Comment by belzebub40k** [comment]
@rubo77 Links to statistics already open in a new new tabs.

**Comment by rubo77** [comment]
Ok, then we have an old version
