### ISSUE TITLE
Offline nodes color less alarming

### ISSUE THREAD

**Issue by rubo77** [ffrgb/meshviewer#289]
I thought about the big red blinking nodes, that gone recently offline:

The big warning character of such nodes is not exactly what we want, those nodes look more prominent than the nodes, that are online.

A better solution could be a  **color fading effect from blue to red**, so you intuitively understand, that this node was recently blue and now is red.

example:

https://codepen.io/rubo77/pen/XGPoXE

**Comment by belzebub40k** [comment]
I think this would be more confusing. Either a node is online or offline. There is not state in between. The time after which a node is considered offline can be controlled via Yanic. I agree that the blinking red circles where to prominent (especially on a low zoom level) but as far as I can tell there is no blinking attribute for offline nodes in the ffrbg meshviewer.

**Comment by xf-** [comment]
It is annoying and distracting. Most warning lights blink for real problems to get attention. This is Map and not css. Change it in your config.
