### ISSUE TITLE
make durations configurable

### ISSUE THREAD

**Issue by rotanid** [ffrgb/meshviewer#32]
there are two hard-coded numbers in the code, would be nice to have them configurable:
https://github.com/ffrgb/meshviewer/blob/develop/lib/map.js#L476
https://github.com/ffrgb/meshviewer/blob/develop/lib/map.js#L480

example solution:
https://github.com/tecff/hopglass/commit/b250eff084a6c32e00b5b6f05acf334d7460d6f7

**Comment by xf-** [comment]
offline 14 days are already used on another place - should be reused.
alert should be a variable.

**Comment by xf-** [comment]
@rotanid maxAge should be fine for offline?

**Comment by xf-** [comment]
Done via https://github.com/ffrgb/meshviewer/pull/37
