### ISSUE TITLE
Wrong node detail page after update to V2

### ISSUE THREAD

**Issue by treblada** [ffrgb/meshviewer#323]
I've updated my node from gluon2016-* to gluon2021-fastd (hood: Umgebung)
After the update there are two nodes with that name in the map's node list, one is inactive (red), the other is active (green).
Both point to the old node's details page, where the status is "offline".

## Expected Behavior
The existing entry for the node is updated. There is only one node in the list and the link directs to a working details page.

## Current Behavior
There are two entries in the node list. Both point the same deprecated details page.

## Steps to Reproduce
One could setup a node with gluon2016 and then update it to gluon2021, but I believe there might be an easier way.

## Your Environment
* Version before: 2016.2-exp20180205 / gluon-v2016.2.7-2-g3d824bd2
* Version now: v2021.1.1-FastD
* Model: TP-Link TL-WR940N v4

**Comment by belzebub40k** [comment]
I assume you are talking about this node: https://map.kbu.freifunk.net/#!/50c7bf7b4326

The Meshviewer at KBU seems to be misconfigured. It includes two meshviewer.json files which both include the node with node_id 50c7bf7b4326.


https://map.kbu.freifunk.net/data/ffkbuu/meshviewer.json
https://map.kbu.freifunk.net/data/ffkbuu-V2/meshviewer.json

**Comment by genofire** [comment]
Maybe KBU should put (only) one yanic server between this domains and generate just one meshviewer.json ....

For me it does not look like a problem of meshviewer.

**Comment by xf-** [comment]
THX @belzebub40k  for looking into issue.

**Detail page**
One mac address for detail page and that is the identifier. Nodes shouldn't be in multiple files. Multiple files are for different networks or special cases like unifi hacky file from their stats.

Like @genofire mentioned, yanic can merge files and provide one single meshviwer.json to avoid such problems or segment the network and no duplicates or provide both the same information.

In general, the meshviewer won't compare a lot and sort entities. A backend with known performance should handle that workload once for all clients. Doing stuff like that on smartphone on large community is a performance penalty for nothing.
