### ISSUE TITLE
rfc: mesh-link saturation based on gw-hops

### ISSUE THREAD

**Issue by AiyionPrime** [ffrgb/meshviewer#326]
## Is your feature request related to a problem? Please describe.

Some in our community dislike the bright red mesh links, that company the few green links that are relevant to batman-adv.
This goes far enough for some of them to switch channels in order to have a better rate of "good" mesh links.

This breaks the redundancy/failover feature of local meshes and is in my experience hard to communicate, and mostly ignored.

## Describe the solution you'd like

Not sure how complicated it would be to aggregate a list of links, that are part of a nodes next hop towards gateways;
but I think it would be pretty interesting to see all other (currently unused) links slightly desaturated.

My goal is not to eliminate either red or green links but to effectively highlight those, that are currently used.

## Describe alternatives you've considered

I thought about the thickness of lines as well, but think partly desaturated unused links would give a cleaner look and a better overview of the effective topology.

## Additional context

On the statuspage of nodes is a "via" section in the middle row:
http://[2001:678:978:214:c66e:1fff:fe9e:3c8c]/cgi-bin/status

I think I saw that in the graph or nodes json as well.

Let me know whether that's clear enough, or if I should provide a picture or something.

**Comment by xf-** [comment]
Wrong place, Meshviewer only a data output.
Stuff like this should be handled on a server.

This also affects layering, needs sorting for links. You could change the colors to something neutral.
