### ISSUE TITLE
Export batman-adv + babeld version to meshviewer.json

### ISSUE THREAD

**Issue by T-X** [ffrgb/meshviewer#327]
## Is your feature request related to a problem? Please describe.

It would be nice if we could track how many babeld and batman-adv nodes and later OLSR nodes are in use where and with which version in Gluon Census. Currently it seems that Yanic is exporting this information to its nodes.json, but Meshviewer does not export it to its meshviewer.json.

**Comment by genofire** [comment]
If you want to expose extra fields in yanic, you could use custom fields:
https://github.com/FreifunkBremen/yanic/blob/main/docs/docs_configuration.md#responddcustom_fields

To show it in meshviewer-ffrgb, could configure it: 

https://github.com/ffrgb/meshviewer/blob/bdb63645387b8e4f678fecb4def65e9b170dd47c/config.default.js#L25
