### ISSUE TITLE
tooltips for icons in upper right corner

### ISSUE THREAD

**Issue by rotanid** [ffrgb/meshviewer#33]
it would be nice for people who don't use meshviewer often to have tooltips for the icons in the upper-right corner.

as an example, we implemented it like this before in our hopglass-fork:
https://github.com/tecff/hopglass/commit/3e04a655c6f6d9655a097f3bd8aae4a36debbc1c

**Comment by xf-** [comment]
I agree, the standalone icon could have some information.
In default i would use shorter Descriptions like a menu title.
If you take a look at leraflet, osm or other maps. All descriptions are short.

**Comment by rotanid** [comment]
i'm not for or against any specific text, i just wanted to raise the issue of tooltips

**Comment by xf-** [comment]
via https://github.com/ffrgb/meshviewer/pull/38

**Comment by xf-** [comment]
resolved via e53d8fc
