### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by tux-84** [ffrgb/meshviewer#336]
Wo finde ich die Dokumentation zum sauberen aufsetzen einer Meshviewer-Instanz?

**Comment by maurerle** [comment]
Wie du leider frustriert festgestellt hast gibt es quasi keine.

Hier mal ein Abriss ohne Garantie auf vollständigkeit:

```
git clone https://github.com/ffrgb/meshviewer
cd meshviewer
npm install
gulp .
cp build /var/www/html/meshviewer
```

Anschließend muss die Config unter `/var/www/html/meshviewer/config.js` noch angepasst werden.

Ich hoffe, dass dir das weiter helfen konnte - könnte man natürlich auch mal ins repo packen.

**Comment by xf-** [comment]
There was no documentation, and after I added a documentation people complained about nonsense. No plan to deploy the documentation and answer nonsense question e.g., how to install a software on Windows? This is a tool that's installed from a community admin, and it runs on a web server.
