### ISSUE TITLE
show number of clients in the local wifi-mesh of a node

### ISSUE THREAD

**Issue by rotanid** [ffrgb/meshviewer#34]
hopglass has a functionality that shows how many clients are connected to nodes in the same wifi-mesh as the current node
maybe we can add that to the ffrgb fork, too?

the pull was there and later one bugfix was added:
https://github.com/plumpudding/hopglass/pull/61
https://github.com/tecff/hopglass/commit/808b8c1986ae943ae6f1152d165786ede146d532
https://github.com/tecff/hopglass/commit/7eb0675be067e5c97e1e1559c176c80806d0c77a

**Comment by xf-** [comment]
undecided - i didn't forget.

Pro:
- Nice feature

Con:
- Lot of code for small feature (don't see any big advantage)
- We list with next merge direct neighbours in Links section
- Consumes performance -> recursive search

**Comment by rotanid** [comment]
the idea of this is so you can tell without calculating yourself, how many clients are in a specific area/building.
but if you're confident the performance penalty is too big, leave it out - or we make it an optional feature, if you don't completely object to optional features that are disabled by default.

**Comment by genofire** [comment]
i would prefere a optional feature

**Comment by SimJoSt** [comment]
As I cannot predict the performance hit, I don't want to say too much, but the feature is interesting.
But as mesh clouds grow and possibly (in the future™) move toward a totally meshed network, I don't know how to deal with it.
Should there be a maximum number of nodes included in the calculations?
Should it be calculated by the machine using the meshviewer (JS) or in the backend for data collection (respond-collector)?
Should the nodes included be limited by how far they are away from each other, to prevent including clients from the next building?
Should the total number of clients of the network be shown, if the network is meshed perfectly?

**Comment by rotanid** [comment]
maybe the performance hit could be circumvented by not displaying/calculating it by default but only after a click on some link or icon

**Comment by xf-** [comment]
I will close this in favour of #69.
It will show clients sorted in different connection types. 10 x 2.4Ghz, 9 x  5Ghz, 5 x LAN Both features will be overkill.

We added client count in "Links"-table.
