### ISSUE TITLE
link-tooltip overlays last line of sidebar information

### ISSUE THREAD

**Issue by SimJoSt** [ffrgb/meshviewer#39]
When selecting a node and scrolling all the way down in the info sidebar, the last line, usually containing information about a link (mesh node or gateway), will be overlayed by the link tooltip containing the full url in Chrome while hovering over a link.
![2017-02-03 14_19_07-einstellungen](https://cloud.githubusercontent.com/assets/2992311/22593767/7e15a4c0-ea20-11e6-9f35-d86bacc76871.png)

**Comment by xf-** [comment]
via 6e6d2b73610d13a6517b4fb5e50669b7463327e3

**Comment by genofire** [comment]
this was only at the tabs, not in the infobox - like in this screenshot

**Comment by xf-** [comment]
fixed in 66f09a2
i wanted to avoid the scollbar and i used the tabs (forgot nodes with many stat images and > 100 vh)
