### ISSUE TITLE
show some replacement string if no hardware modell was supplied in statistics tab

### ISSUE THREAD

**Issue by SimJoSt** [ffrgb/meshviewer#46]
At Freifunk Bremen gateways also deliver data to nodes.json and are listed in the meshviewer.
In the statistics tab their firmware version is their version of debian. As they don't deliver a hardware modell there is a line in the modell sections which has no string at all, but says there are 6 devices.
Without a string to click on, I cannot filter these specific devices.

There should be some kind dummy string like "no data provided". It's also possible to filter them out entirely.

**Comment by SimJoSt** [comment]
Also a problem with the "Site" section.

**Comment by SimJoSt** [comment]
hardware modells
![2017-02-06 02_26_08-freifunk bremen](https://cloud.githubusercontent.com/assets/2992311/22631817/b380974c-ec13-11e6-952a-78e69370efcd.png)

site section
![2017-02-06 02_26_22-freifunk bremen](https://cloud.githubusercontent.com/assets/2992311/22631818/b3a35cdc-ec13-11e6-8f2e-71c2be0e3a5f.png)

**Comment by xf-** [comment]
Site can be mapped and named via config.json.
About the model, all offloader and other nodes provide information's. maybe something missing in config.

**Comment by genofire** [comment]
The Problem is, that the gateway/vpn of use has no values for site and hardware model:
https://github.com/ffnord/ffnord-alfred-announce
the [respondd-collector](https://github.com/FreifunkBremen/respond-collector/) has no [aliases.json](https://github.com/ffnord/ffmap-backend/blob/master/aliases.json_sample) like the [ffmap-backend](https://github.com/ffnord/ffmap-backend/)

**Comment by genofire** [comment]
should be fixed with: https://github.com/FreifunkBremen/respond-collector/commit/3e342ce7383aa30cee6ee5f2d3db5f7759e30043

and/or

https://github.com/ffnord/ffnord-alfred-announce/pull/20
and in the config.json a
```json
"siteNames" :[
{
      "site": "",
      "name": "Freifunk Bremen"
},...
]
```
