### ISSUE TITLE
show type of mesh link (like hopglass)

### ISSUE THREAD

**Issue by SimJoSt** [ffrgb/meshviewer#69]
In the node info card of hopglass, additionally to TQ and distance, there is another column which displays the type of mesh link (wifi, lan or fastd):
![2017-02-14 14_21_25-freifunk altdorf_ ff-nsv-eisenwaren-clemente](https://cloud.githubusercontent.com/assets/2992311/22930509/ea1fc0b2-f2c0-11e6-9ee6-a4d7cdf21def.png)
Source: https://map.tecff.de/#!v:m;n:60e327be1d7a

It would be nice to have this also in the meshviewer, as this provides more transparency for the mesh.
If this feature is only achievable bit data providers like respond-collector or hopglass-server, I will transfer this suggestion to Bremen fork.

**Comment by genofire** [comment]
Lol, this node is offline (since 3h) and the links are still in the map ...

**Comment by rotanid** [comment]
the node wasn't offline - that's just the ath9k bug.
thanks to respondd/hopglass-server the surrounding nodes show that there is a node, which itself doesn't report anything anymore.

**Comment by genofire** [comment]
I am sorry, i think this information are not in the normal `graph.json`, as we implement `graph.json` in respond-collector we got a bug, that a lot of nodes become duplicated in forcegraph during storeing this information.

**Comment by xf-** [comment]
Should be possible.

Problems:
- We should use translations -> sanitize string and look in locale
  - Unknown strings are possible
  - Mixup in source language Kabel (german), Wifi, fastd, L2TP

**Comment by genofire** [comment]
I was wrong, there is VPN flag in the graphs

**Comment by xf-** [comment]
#81

**Comment by xf-** [comment]
Info is not available in ffmap-backend or yanic.
We can only shown if it is VPN connection (isGateway) and everything else.

Please reopen if the info is available (Kabel, Wifi).

**Comment by rotanid** [comment]
@genofire do you plan on implementing this in yanic?

**Comment by genofire** [comment]
We have only Tunnel, Wireless, Others as option.
Maybe we will, but at the moment have some other interesting things on the pipe and nobody has ask.

**Comment by rotanid** [comment]
hm, isn't this enough then, having these 3 options? i don't know of any other type than those three, so it should be sufficient

**Comment by xf-** [comment]
I current version we have only fastd and and N/A based on is one side a gateway. No info in json file.

**Comment by genofire** [comment]
https://github.com/FreifunkBremen/yanic/issues/45, not today but maybe it will 😄
