### ISSUE TITLE
RFC: meshviewer organisation

### ISSUE THREAD

**Issue by SimJoSt** [ffrgb/meshviewer#70]
We have talked about this in the IRC channel several times in the last months and I would like to have the results a little more public and permanent.

### benefits
- more "official" place to develop
    - this makes it more obvious that this software is used and developed by multiple communities
- the possibility of a `respond-collector` branch
    - to provide communities which are not using the ffmap-backend for data collection anymore a version of the meshviewer they can install
    - this fixes having the main development on https://github.com/ffrgb/meshviewer and the additional development for new data providers at https://github.com/FreifunkBremen/meshviewer-ffrgb/tree/respondd
    - could be merged into `develop` after support for Alfred has been officially dropped for some time
- possibility to further develop the https://github.com/FreifunkBremen/respond-collector in the org side by side with the meshviewer
    - as the development of Gluon will lead to dropped support of Alfred in the future there is a need for an alternative way of collecting data  
      as from the discussion in the IRC channel, all existing software except the respond-collector was deemed to have poor code quality or other downsides, like code platform
- possibly more maintainers
- ability to define a clear policy for code and prs
    - at the moment many creators of issues and prs have to ask @xf- first, if this kind of feature might have a chance of merging
    - the current system of mainly working from prs and requesting review, works quite well to keep the code clean

### downsides
- more expectations
    - admins who deploy the software aswell as users will be more like to expect new features and support
- some work to set it up

*The list will be edited and will expand with other reasons supplied by commenters.*

**Comment by genofire** [comment]
I hope and wish the `respondd` branch would sometime merged - there are everywhere `if` so the `nodes.json` of v2 is also supported

**Comment by xf-** [comment]
- more "official" place to develop
    - this makes it more obvious that this software is used and developed by multiple communities

> No intention to do that. I will stay with my development in this organization. Contribution is low with < 10 commits from > 170 commits. Most communities using this fork maybe send a BUGFIX but almost no Features. (not included translations and review work)

- the possibility of a `respond-collector` branch
    - to provide communities which are not using the ffmap-backend for data collection anymore a version of the meshviewer they can install
    - this fixes having the main development on https://github.com/ffrgb/meshviewer and the additional development for new data providers at https://github.com/FreifunkBremen/meshviewer-ffrgb/tree/respondd
    - could be merged into `develop` after support for Alfred has been officially dropped for some time

> We use Alfred (not my choose) and a lot of other communities also use Alfred (a lot with v1 nodes.json). I personally want to avoid the overhead with more and more information's.

- possibly more maintainers

> I have no problems with more maintainers

<hr>

A lot of forks exists and performance is poor. Larger communities have to suffer for optional features. larger nodes.json. Mobile devices have limited resources and power. My intention is still to develop a tool for users and not sysadmins. I have no problems with a fork and somebody maintaining all reports and issues. Also clear issue about name or other stuff.

**Comment by SimJoSt** [comment]
> We use Alfred (not my choose) and a lot of other communities also use Alfred (a lot with v1 nodes.json). I personally want to avoid the overhead with more and more information's.

I just wanted to point out, that Alfred will not be here forever, as Gluon wants to part with it.

>No intention to do that. I will stay with my development in this organization. Contribution is low with < 10 commits from > 170 commits. Most communities using this fork maybe send a BUGFIX but almost no Features. (not included translations and review work)

> A lot of forks exists and performance is poor. Larger communities have to suffer for optional features. larger nodes.json. Mobile devices have limited resources and power. My intention is still to develop a tool for users and not sysadmins. I have no problems with a fork and somebody maintaining all reports and issues. Also clear issue about name or other stuff.

I don't understand if you are for or against an own org.
I realize that you do 98 % of the coding and that you want to follow your current style, but I could not determine your thoughts on the way moving forward.

**Comment by xf-** [comment]
> I don't understand if you are for or against an own org.

I don't want a new org. All meshviewers or other smaller solutions are developed by a community and maybe have similar to this org a new group for meshviewer repo to allow more contributors. A new org provides overhead and stuff i don't want to deploy will be merged. Same problem again and result is a fork again.

Bashing alfred has no influenza on merging or developing stuff....

**Comment by SimJoSt** [comment]
> Bashing alfred has no influenza on merging or developing stuff....

That was not the intention :-)
Just wanted to point out, that a move to a new system seems unavoidable in the future. 

Thank you for your opinion.
And with the current information, the state of software and opinions I agree.
