### ISSUE TITLE
[BUG] Zoom buttons use center of browser window, not visible map

### ISSUE THREAD

**Issue by SimJoSt** [ffrgb/meshviewer#82]
## Expected Behavior

When pressing the plus button, I expect the map to zoom one level in, centered around the map I can see (visible map area).

## Current Behavior

The map zooms in on the center of the browser window.

**Comment by xf-** [comment]
Leaflet supports a sidebar and most features like bounds work with it. Zoom ignores it.

**Comment by SimJoSt** [comment]
There is now way to set a specific center? Every time I scroll with my mouse, a center to zoom into is set...

**Comment by xf-** [comment]
http://leafletjs.com/reference.html#control-zoom - i see no option like in fitBounds https://github.com/ffrgb/meshviewer/blob/develop/lib/map.js#L345

**Comment by xf-** [comment]
I found no nice solution, i will take a look again after #85 is finished. Any hint or PR is welcome.

**Comment by xf-** [comment]
https://github.com/Mappy/Leaflet-active-area/blob/leaflet-1.0/src/leaflet.activearea.js could resolve this

**Comment by genofire** [comment]
Cool, but we use already 1.0.3 - maybe patch it own or wait :/

**Comment by xf-** [comment]
master should be v1 compatible. a lot of code for this fix. i will test it later or you can try it @genofire
