### ISSUE TITLE
Move documentation

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#86]
## Current Behavior

Every improvement needs a commit - unclean history.

## Possible Solution

- Website
- 3-rd party service

**Comment by SimJoSt** [comment]
What about a Github-Wiki?
Easy and fast to edit. I think it's even possible to make changes need approval.
Gluon uses it as well.

**Comment by xf-** [comment]
No GitHub-Wiki. Overview is bad + no search.
Git is nice, but not really useful.

I took a look at gluon, features like ``\`format for Codeblock highlighting aren't used.

Most gluon stuff is on http://gluon.readthedocs.io/en/latest/#

**Comment by genofire** [comment]
Branch, Folder ? How write whats?

**Comment by xf-** [comment]
GitBook test: Looks really nice, fast, e-books and online readable. Supports markdown and also offline editors
https://www.gitbook.com/book/meshviewer/documentation/details

**Comment by xf-** [comment]
If nobody has something against i will move the documentation to gitbook or self-host it.
@genofire @SimJoSt or anybody who is interested...
