### ISSUE TITLE
Evaluation of Netjson

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#87]
## Context

Use a standard and replace nodes.json.
Netjson has a RFC and documentation.
http://netjson.org/

**Comment by genofire** [comment]
I would also be for `graph.json` - http://netjson.org/rfc.html#rfc.section.7 has a collection storage option.
During think on multisite / multiple source we should think on recursive reading of collections in collections.

**Comment by xf-** [comment]
I think correctly it has no advantage. If yanic works with netjson internally, it could be more interesting to only apply some kind of filter. Meshviewer needs to avoid overhead for slow clients
