### ISSUE TITLE
Remove colors from javascript

### ISSUE THREAD

**Issue by genofire** [ffrgb/meshviewer#91]
A idea on which way?

**Comment by xf-** [comment]
my idea was to create 2 json files and put a base config into meshviewer (all settings are present no if needed), second one is current config and will be merged and overwrites the default values. Best merge would be via grunt, less code/rewrite.

**Comment by genofire** [comment]
a json is uncool, because we have to rewrite so many part for get it between require moduls loaded and defined modul return the function.

I write a constance and color modul which return just a object.

**Comment by xf-** [comment]
The merge is implemented. Please notice it is no deep merge.

**Comment by xf-** [comment]
I started with this one, but i'm not sure what is the bets way to go.

- Global config via var config would be easy and everywhere available, but not scoped and could cause issues (meshviewer is normally standalone = no issue). RequireJs is not designed for that.
This will cause less autocomplete and warnings/notices in IDE - 'might not be defined'
- We can export the config and define in every needed file.
- Use current solution an pass the config from object to object via constructor.

@ffrgb/meshviewer what do you think?

**Comment by genofire** [comment]
Option 2
