### ISSUE TITLE
Grunt cachebreaker breaks Esri.WorldImagery tile URL

### ISSUE THREAD

**Issue by oliver** [ffrgb/meshviewer#98]
At https://map.ffhb.de the Esri.WorldImagery map layer does not work. I think this is caused by the "cachebreaker" Grunt task.

## Expected Behavior
When visiting the meshviewer at https://map.ffhb.de and selecting the Esri.WorldImagery layer in bottom right corner, some kind of map or satellite tiles should be displayed.

## Current Behavior
When selecting the Esri.WorldImagery layer in bottom right corner, no map tiles are displayed. Firefox Inspector shows that all tile requests for ESRI tiles fail with error 400 (Bad Request).

## Possible Solution
Firefox Inspector shows that tile requests go to eg. https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery1489402133798z%7D/668/1077 . The original URL configured in config.json is //server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x} . In the index.html deployed on map.ffhb.de server this becomes //server.arcgisonline.com/ArcGIS/rest/services/World_Imagery1489402133798z}/{y}/{x} .

I suspect that the Grunt cachebreaker task replaces the "/MapServer/tile/{" part from the ESRI tile URL, since that part is enclosed in "y" and "z". I don't understand enough about Grunt to confirm or fix this though.

## Your Environment
I don't know exactly how the index.html on map.ffhb.de is built, but I would expect that it uses the standard Gruntfile.

**Comment by xf-** [comment]
I think your assumption is correct. I found no better grunt module. I try to choose a better string.

**Comment by xf-** [comment]
fixed via c235686
